<?php
class Config {
	
	private $reg;
	private $date;
	private $time;
	
	public function __construct($reg) {
		$this->reg = $reg;
		date_default_timezone_set('America/New_York'); 
		$this->date = date('dmY');
		$this->time = date('H:i:s');
		}
		
	public function getSiteConfig() {
		//on ouvre le fichier de config en mode text pas de html
		if(file_exists(DIR.SITE_DEFINE_EDITABLE)){
			$fp = @fopen(DIR.SITE_DEFINE_EDITABLE, 'r');
			if($fp){
				$content = @fread($fp, filesize(DIR.SITE_DEFINE_EDITABLE));
				$content = str_replace("\\n", "", $content);
				@fclose($fp);
				}
			//on place le content dans des vars avec le nom du define
			$arrMatches = array();
			$pattern = "/define\('([0-9A-Z_\s]*)'\, '([\\\\a-z0-9A-Z_@*:<>\/!-.?\s]*)'\);\/\*([\\\\=a-z0-9A-Z_@*:<>\/!-.?\s]*)\*\//"; 
			preg_match_all($pattern, $content, $arrMatches);
			if(count($arrMatches)){
				return $arrMatches;
				}
			}
		return false;
		}	
		
	public function setSiteConfig($arr){
		$arrValues = array();
		if(isset($arr) && is_array($arr) && count($arr)){
			foreach($arr as $k=>$v){
				if(isset($arrValues[$v['name']])){
					$arrValues[$v['name']]['comments'] = $v['value'];
				}else{
					$arrValues[$v['name']] = array('data' => $v['value']);
					}
				}
			if(is_array($arrValues) && count($arrValues)){
				$fp = @fopen(DIR.SITE_DEFINE_EDITABLE, 'w');
				if($fp){
					$str = '<?php'.EOL;
					$str .= '/* autogenerated file by admin/class/config.php */'.EOL;
					$str .= EOL;
					@fwrite($fp, $str);
					foreach($arrValues as $k=>$v){
						$str = 'define(\''.$k.'\', \''.$v['data'].'\');/*'.$v['comments'].'*/'.EOL;
						@fwrite($fp, $str);
						}
					@fwrite($fp, EOL.'//END');	
					@fclose($fp);
					return true;
					}
				}
			}
		
		return false;	
		}	
		
		
	}
?>