<?php
/* autogenerated file by admin/class/config.php */

define('SITE_NAME', 'INSPQ');/*the site name*/
define('ENABLE_CACHING', '0');/*enable sql query cashing: yes = 1, no = 0*/
define('SHOW_DEBUG', '0');/*show debug: yes = 1, no = 0*/
define('SITE_IS_DOWN', '0');/*site offline: yes = 1, no = 0*/
define('SIMPLIFIED_URL', '0');/*show simplified url: yes = 1, no = 0*/
define('META_CREATOR', 'INSPQ');/*the creator of the site*/
define('META_TITLE', 'INSPQ');/*the basic title of the site*/
define('META_DESCRIPTION', 'INSPQ');/*the basic description of the site*/
define('META_KEYWORDS', 'INSPQ');/*the basic keyword of the site*/
define('LANG_ENABLED', 'fr_CA');/*all languages enabled comma seperated*/
define('LANG_DEFAULT', 'fr_CA');/*the lang by default*/
define('EMAIL_ORIGINE_COURRIEL', '');/*the address from witch email are sent*/
define('EMAIL_ORIGINE_NOM', 'INSPQ');/*the name showing in the email*/
define('REMOTE_ADDR_ACCEPTED', '');/*remote address that can access the site when it's offline*/

//END